### ISSUE TITLE
It can not work without spark

### ISSUE THREAD

**Issue by qins** [MeaneyLab/PRSoS#3]
Nice work. Worked perfectly after installed spark.
Can it work without spark?

**Comment by lchen-mcgill** [comment]
Thank you for your comment, @qins. 
PRSoS utilizes Apache Spark's distribution framework for processing operations (e.g., reading data in parallel) so it must work with Apache Spark. 

P.S. - I apologize for the delayed response (I did not realize I was not getting email notifications for this repository).

**Comment by qins** [comment]
Thanks for your kindly reply. I was wondering there maybe someone who want to use PRSoS, but can not install spark or has no spark.
