### ISSUE TITLE
PRSoS new user question

### ISSUE THREAD

**Issue by BCI-Barts** [MeaneyLab/PRSoS#4]
Hi there - new to this great piece of bioinf software...

Apologies if this already exists and I haven't seen it, 
but I was hoping that you could let me know if its 
possible to run the software in a mode where all snps are printed
out for all sets at each threshold for each phenotype
and/or a max group of snps size could be set within
each threshold....

**Comment by lchen-mcgill** [comment]
Hi BCI-Barts,

Thank you for the question. The software prints the list of SNP IDs at each threshold in a separate output file (*.snplog.csv) if you specify --snp_log in the command. 

It also prints the number of SNPs in each PRS per subject sample in the final output--this can vary if your samples are missing genotype calls. If you use imputed posterior probabilities (dosage data) in your genotype data, the number of SNPs would be equivalent to the max size of the SNP group with each threshold. The max group of SNP size within each threshold can also be checked by counting the number of SNPs in the *.snplog.csv output by column for each threshold. This is most easily done in a spreadsheet viewer program (e.g., Excel, R).
